### ISSUE TITLE
static port of module

### ISSUE THREAD

**Issue by sergeywp** [sap-archive/com.sap.openSAP.hana5.example#10]
Good morning!
I faced with problem - when you redeploy XSA application, for different module XSA assigns random ports. I need to assign static port to module. I saw documentation and I found there that in mta.yaml there is parameter port in scope of module, which I can use. As I understood It could help to solve issue. 
![xsa_issue](https://user-images.githubusercontent.com/13301501/43820620-2e350d5a-9b00-11e8-8f55-b3df96a3399a.PNG)
I put those parameter in mta.yaml in Parameters of module:
![image](https://user-images.githubusercontent.com/13301501/43821297-3787d714-9b02-11e8-9416-38416de9d312.png)
![image](https://user-images.githubusercontent.com/13301501/43821409-879205ae-9b02-11e8-899d-b0d200a9c626.png)

But When I run It - It fails with message in log:
 "Unexpected type Double for option "port" of app "qs1svgEnowhBkHra-testPort-uiPort", expected Integer!"
![xsa_issue_s](https://user-images.githubusercontent.com/13301501/43821476-c25c2ff2-9b02-11e8-936e-d5d83b0cea07.PNG)

Do you know, is it possible to fix port in application? 
And may be I make It wrong?

**Comment by jung-thomas** [comment]
The Web IDE builder actually only supports a small subset of all the deployer parameters although this looks like a bug to me since its seeing it as a Double.  However I wouldn't put the port in the mta.yaml anyway. I'd suggest supplying at deploy time only via mtaext file just like we do with the installation of the SAP Web IDE itself. 

It really isn't suggested to try to use lots of static ports however. If you don't like the dynamic port assignment, the the correct solution would be to use hostname based routing instead.
