### ISSUE TITLE
Moving file cause "xs deploy" to fail

### ISSUE THREAD

**Issue by himanshuPandey25** [sap-archive/com.sap.openSAP.hana5.example#6]
Hi,
I am using HANA Express 2.0 with web ide version  4.2.18.
I moved a file from one folder to another and while deploying to test space (`xs deploy <mtar>`) I got an error:

>  Merging... ok
3/9/18 6:49:23.421 AM [APP/2-1/deploy] OUT        Error: "calc.scenario://requestStatus": the object cannot be provided more than once [8212002]
3/9/18 6:49:23.421 AM [APP/2-1/deploy] OUT         "src/modelling/requestStatus.hdbcalculationview": the file would provide it
3/9/18 6:49:23.421 AM [APP/2-1/deploy] OUT         "src/requestStatus.hdbcalculationview": the deployed file already provides it
3/9/18 6:49:23.421 AM [APP/2-1/deploy] OUT        Error: "db://requestStatus": the object cannot be provided more than once [8212002]
3/9/18 6:49:23.421 AM [APP/2-1/deploy] OUT         "src/modelling/requestStatus.hdbcalculationview": the file would provide it
3/9/18 6:49:23.421 AM [APP/2-1/deploy] OUT         "src/requestStatus.hdbcalculationview": the deployed file already provides it
3/9/18 6:49:23.421 AM [APP/2-1/deploy] OUT        Error: "db://requestStatus/hier/requestStatus": the object cannot be provided more than once [8212002]
3/9/18 6:49:23.421 AM [APP/2-1/deploy] OUT         "src/modelling/requestStatus.hdbcalculationview": the file would provide it
3/9/18 6:49:23.421 AM [APP/2-1/deploy] OUT         "src/requestStatus.hdbcalculationview": the deployed file already provides it
3/9/18 6:49:23.421 AM [APP/2-1/deploy] OUT       Error: Calculating dependencies... failed [8212108]
3/9/18 6:49:23.421 AM [APP/2-1/deploy] OUT       Error: Could not compose a consistent make graph [8212012]

But the build in development space using web-ide is fine.
Is there any way to deploy it, other than moving the file back to its original position?
Is it a possible bug which got fixed in later patches?

Regards,
Himanshu

**Comment by himanshuPandey25** [comment]
One more issue.
I renamed and refactor my calculation view and then deployed the app. It deployed (and i thought that I can again deploy it after renaming to original), but the old view was still there even when no file is present for it........
![image](https://user-images.githubusercontent.com/7977558/37199381-73b5ca98-23a7-11e8-907a-f6c0eeb6dc58.png)

**Comment by jung-thomas** [comment]
The issues here should relate directly to the source code of this project. It is not a general Q/A for everything HANA development.  For general questions please use: https://answers.sap.com/index.html

For the answer to your question please refer to the documentation of the hdi-deploy module. It describes the options for deletion during deployment (which the Web IDE sets automatically for you but you must do manually upon a "real" deploy).  Here is the section from the help for your convenience:

In normal operation, the HDI Deployer will schedule only the set of added and modified files for deployment. The set of deleted files is not scheduled for undeployment.

In order to undeploy deleted files, an application needs to include an undeploy whitelist via an undeploy.json file in the root directory of the db module (right beside the src/ and cfg/ folders). The undeploy whitelist undeploy.json file is a JSON document with a top-level array of file names:

undeploy.json:

[
    "src/Table.hdbcds",
    "src/Procedure.hdbprocedure"
]
The file must list all artifacts which should be undeployed. The file path of the artifacts must be relative to the root directory of the db module and must use the HDI file path delimiter '/'.

For interactive scenarios, it's possible to pass the auto-undeploy option to the HDI Deployer, e.g.

node deploy --auto-undeploy
In this case, the HDI Deployer will ignore the undeploy whitelist undeploy.json file and will schedule all deleted files in the src/ and cfg/ folders for undeployment.

**Comment by himanshuPandey25** [comment]
Thanks and sorry for opening a issue here. I am following this repo for most of the queries and thought of reaching out to you.
